// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gov.dhs.efile.domain;

import gov.dhs.efile.domain.ApplicantIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplicantIntegrationTest_Roo_Configurable {
    
    declare @type: ApplicantIntegrationTest: @Configurable;
    
}
